{{- if and .Values.rbac.create .Values.rbac.clusterRole }}
apiVersion: rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-node-watcher.fullname" . }}
  labels:
    {{- include "k8s-node-watcher.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-node-watcher.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-node-watcher.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
